### ISSUE TITLE
Fine Tune Elder Wand

### ISSUE THREAD

**Issue by prishadargan** [prishadargan/road-runner-quickstart-master-master#8]

**Comment by karthikpalled** [comment]
while (gamepad1.dpad_up) {
                double position1 = robot.ElderWand.getPosition();
                position1 = position1 + 0.01;
                robot.ElderWand.setPosition(position1);
                sleep(50);
             }

            while (gamepad1.dpad_down) {
                double position2 = robot.ElderWand.getPosition();
                position2 = position2 - 0.01;
                robot.ElderWand.setPosition(position2);
                sleep(50);
            }
